### ISSUE TITLE
Can The Parent Read The Child Window Contents

### ISSUE THREAD

**Issue by NJseo** [crookse/cdc-parent-window-child-iframe#1]
Can The Parent Read The Child Window Contents

**Comment by crookse** [comment]
Hey @NJseo,

Sorry my original answer below answers the question of, "Can the parent send a message to it's child iframe," and doesn't answer your question. If you just want to read the contents of the child window, then you can send a GET request for it's HTML using an XMLHttpRequest object or an AJAX call.

Example AJAX:

```javascript
$.ajax({
  method: "GET",
  url: "http://dev.iframe.com",
  success: (response) => {
    console.log(response);
  }
});
```

Example XMLHttpRequest:

```javascript
var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
    console.log(xhttp.responseText);
  }
};
xhttp.open("GET", "http://dev.iframe.com");
xhttp.send();
```

If you're interested in having the parent send data to its child iframe and having the child iframe send data back depending on the message that the parent sent, then you can take the example code below and apply it accordingly.

---

The parent window can send its child iframe messages. It's basically the same code, but the code is reversed (parent gets iframe's code and iframe gets parent's code) and the `targetWindow` in `targetWindow.postMessage()` is the iframe's `window` object. How do you do it? Read below.

**_Note: The example code below assumes you're using jQuery._**

1. In the parent window, add the function that sends a message to the child iframe:

    ```javascript
    <script type="text/javascript">
      function sendMessageToChild(message) {
        // Call postMessage on the child iframe's window object
        // (See https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow
        // for more information on getting the window object of an iframe element)
        $("iframe")[0].contentWindow.postMessage(message, $("iframe").attr("src"));
         console.log("Sent message to the child iframe.");
      }
    </script>
    ```

2. In the child iframe, add the logic that handles messages sent from other windows:

    ```javascript
    <script type="text/javascript">
      // Determine how the browser should listen for messages from other
      // windows. If `addEventListener` exists, then use that. Otherwise, use
      // `attachEvent` because an older browser is probably being used. Also,
      // use a callback to handle messages so that both methods of "message
      // listening" can be routed to the same function. The callback in this
      // example is `handleMessage` and it will take one argument (the
      // `MessageEvent` object).
      if (window.addEventListener) {
        window.addEventListener("message", handleMessage);
      } else {
        window.attachEvent("onmessage", handleMessage);
      }

      /**
       * Handle a message that was sent from some window.
       *
       * @param {MessageEvent} event The MessageEvent object holding the message/data.
       */
      function handleMessage(event) {
          console.log("Received a message from " + event.origin + ".");
    
          // If the window that sent this message is not the parent window, then
          // don't process the message.
          if (event.origin != "http://dev.parent.com") {
              console.log("The message came from some site we don't know. We're not processing it.");
              return;
          }
    
          // When one window sends a message, or data, to another window via
          // `{targetWindow}.postMessage()`, the message (the first argument) in the
          // `{targetWindow}.postMessage()` call is accessible via `event.data` here.
          var dataFromParentWindow = event.data;
    
          console.log(dataFromParentWindow);
      }
    </script>
    ```

3. Open up your project in the browser and type the following in the console:

    ```javascript
    sendMessageToChild("Hello, child iframe!");
    ```

_**Note: You might see `undefined` pop up in the console. That doesn't mean the code is broken. That's going to happen because `sendMessageToChild()` doesn't return anything.**_

**Comment by NJseo** [comment]
Yeah, essentially I was wanting to take a third party iframe and scrape its contents. It appears your solution requires the child and the parent to cooperate.

Thank you though.
